name: Run Tests

on:
  push:
    branches: [main, testes]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com Vitest
        run: npm run test